Add basic patches for FDCAN
stm32-rs/stm32-rs pull request #478
Opened 2021-01-10 17:35 UTC by richardeoin

FDCAN appears in the H7, G4, L5 and MP1 families. The peripheral varies between the families, with the G4/L5 versions being somewhat simpler. I don't see any variation within families, but haven't exhaustively checked for this.

On the H7, the FDCAN2 doesn't support TTCAN. However FDCAN2 is `derivedFrom="FDCAN1"` in the original ST SVDs (and remains so). The RM isn't very clear about which registers are missing from FDCAN2, but we could to remove the `TT*` registers from FDCAN2 if this is important.

G4 devices have either 1 or 3 FDCANs.

Checked against:
H7 RM0399
G4 RM0440

2021-01-29 02:17 UTC, adamgreig requested changes
Thanks, this looks great and must have been a real pain. I just found three typos, everything else is ready to merge.

2021-01-29 02:17 UTC, adamgreig commented on devices/common_patches/fdcan/fdcan_g4.yaml
> +      REFL:
```suggestion
      TEFL:
```

2021-01-29 02:17 UTC, adamgreig commented on devices/common_patches/fdcan/fdcan_g4.yaml
> +      REFLE:
```suggestion
      TEFLE:
```

2021-01-31 20:37 UTC, richardeoin commented
Thanks for the thorough review as always! It was a little tedious, but not too bad

2021-02-01 00:18 UTC, adamgreig approved these changes

2021-02-01 00:18 UTC, adamgreig commented
Thanks!

bors merge

2021-02-01 00:27 UTC, merged