STM32L5: add GPIO enum values
stm32-rs/stm32-rs pull request #479
Opened 2021-01-10 18:42 UTC by kenbell

This change replicates the approach taken for the L0 family.  Note: in L0 and L5 families, the documentation has the Alternate Function selection documented as 'AFSEL', rather than 'AFR', so generic gpio_v2 patch does not apply.

2021-01-20 08:20 UTC, deadprogram commented
Hello, friendly maintainers of this project. We would oh so my much like to have this contribution land so we can use it. Thank you!

2021-01-20 17:49 UTC, adamgreig requested changes
Thanks for the PR, and the ping! This looks fine to merge except this one tweak to the description text.

2021-01-20 17:49 UTC, adamgreig commented on peripherals/gpio/gpio_l5.yaml
> +      Analog: [3, "Analog mode"]
On the L5, the reset state is actually analog mode (except for the SWD/JTAG pins):

```suggestion
      Input: [0, "Input mode"]
      Output: [1, "General purpose output mode"]
      Alternate: [2, "Alternate function mode"]
      Analog: [3, "Analog mode (reset state)"]
```

2021-01-21 04:04 UTC, adamgreig approved these changes
Thanks!

bors merge

2021-01-21 04:12 UTC, merged