[stm32f7] Fix SYSCFG register
stm32-rs/stm32-rs pull request #612
Opened 2021-09-01 17:01 UTC by maximeborges

Following #606, fix fields  in SYSCFG for every F7 chips

2021-09-06 22:48 UTC, adamgreig commented
Could you rebase this now that the timers PR is merged? It would make it easier to review and to compare the memory maps.

2021-09-07 07:48 UTC, maximeborges commented
> Could you rebase this now that the timers PR is merged? It would make it easier to review and to compare the memory maps.

Done.

2021-09-07 22:33 UTC, adamgreig commented on devices/common_patches/f730_f7x2_f7x3_syscfg.yaml
> +      - I2C*
I don't understand these deletions, it looks like RM0431 has the I2C and PB fields in PMC, and doesn't have the MII_RMII_SEL? Whereas RM0410 does have MII_RMII_SEL as well as PB and I2C, and only RM0385 (stm32f745, f750, f7x6) has the MII_RMII_SEL but no PB/I2C fields.

2021-09-07 22:36 UTC, adamgreig commented on devices/stm32f7x6.yaml
> +      - I2C*
Looking at the [memory map](https://github.com/stm32-rs/stm32-rs-mmaps/compare/pr-612-1212829#diff-f146746c79235e17e7a8674bbb31537af0c2d61e3d3552ab34f078fed0fd67d8) it doesn't seem like these deletions are doing anything?

2021-09-07 22:37 UTC, adamgreig requested changes
Thanks! This looks mostly sensible but I didn't totally follow the deletions from the PMC register:

2021-09-09 00:31 UTC, adamgreig commented on devices/common_patches/f730_f7x2_f7x3_syscfg.yaml
> +      - I2C*
I don't know why 0385 doesn't have them, but they're not in any version of the RM and no mention of it in the errata... I don't have any of those F7 to test with. Maybe ST's HAL has clues? I think we can leave them out for now and add later if it turns out they should be here.

2021-09-09 00:40 UTC, adamgreig approved these changes
All looks good now, thanks. As mentioned in the comment, we can add the FMP fields to 745/750/7x6 (RM0385) later if they do actually exist.

bors merge

2021-09-09 00:49 UTC, merged