stm32wl: add register descriptions for dual-core variants
stm32-rs/stm32-rs pull request #628
Opened 2021-09-16 03:16 UTC by newAM

This adds register descriptions for registers that are exclusive to the dual-core STM32WL's

cc @jorgeig-space

2021-09-16 03:34 UTC, newAM commented on peripherals/flash/flash_wl.yaml
> +    PNB: [0, 0x7F]
I think this is an error in the STM32WLE reference manual, the STM32WLE manual only goes from page 0 - 63 (the value should be 0x3F in that case), but in the STM32WL5X reference manual this goes from 0 - 127.

As far as I can tell the STM32WLE is capable of programming its whole 256K, same as the STM32WL5X.

2021-09-29 23:49 UTC, adamgreig requested changes
Thanks, this looks good! I just noticed a couple of minor typos, I'll add the fixes for those and get this merged.

2021-09-29 23:49 UTC, adamgreig commented on peripherals/ipcc/ipcc_wl.yaml
> +      Clear: [1, "Processor receive channel n status bit set"]
```suggestion
      Set: [1, "Processor transmit channel n status bit set"]
      NoAction: [0, "No action"]
    "CH[1-6]C":
      Clear: [1, "Processor receive channel n status bit clear"]
```

2021-09-29 23:49 UTC, adamgreig commented on peripherals/flash/flash_wl_c2.yaml
> +    IPCCDBA: [0, 0x1FFF]
```suggestion
    IPCCDBA: [0, 0x3FFF]
```

2021-09-29 23:50 UTC, adamgreig approved these changes
bors merge

2021-09-30 00:02 UTC, merged