STM32L4x5: Add GPIOx ASCR & BRR registers
stm32-rs/stm32-rs pull request #680
Opened 2021-12-21 13:47 UTC by MathiasKoch

Fixes https://github.com/stm32-rs/stm32-rs/issues/342

2022-01-14 20:43 UTC, richardeoin requested changes
Thanks for the PR! Couple of comments:
* The RM describes the BRR / ASCR registers with a series of one-bit fields `BRR0`, `BRR1`, ... and this is the case for all the other GPIO register definitions also. I think this would be preferred instead of a 16-bit field for consistency if nothing else
* BRR is also missing on stm32l4x1, stm32l4x2, stm32l412, stm32l4x3. These are parts that don't have ASCR, so it would make sense to split the patch file and apply the BRR section to stm32l4x1.. also

2022-01-14 20:43 UTC, richardeoin commented on devices/common_patches/l4_gpio_ascr_brr.yaml
> +          access: read-only
Guess this should be `write-only`

2022-01-15 16:52 UTC, MathiasKoch commented
@richardeoin Thanks for the feedback.

I believe this should address all your points?

2022-01-16 18:57 UTC, richardeoin approved these changes
Perfect, thanks!

bors r+

2022-01-16 19:56 UTC, richardeoin approved these changes
Tidied merge conflict

bors r+

2022-01-16 20:23 UTC, richardeoin commented
Not sure why CI failed. Let's retry

bors retry

2022-01-16 20:30 UTC, merged

2022-01-16 21:12 UTC, burrbull commented
Enums in common_patches