Added H5
stm32-rs/stm32-rs pull request #811
Opened 2023-03-21 15:11 UTC by David-OConnor

Fixes #810 

Missing some things. Latest error is `make: *** No rule to make target 'stm32h5'.  Stop.`

2023-03-22 00:31 UTC, David-OConnor commented
The basics are here; not sure how to locate which patches to apply. I attempted `matchperipherals.py`, but didn't find matches for any of the peripherals I tried. There are many things broken or inconsistent with existing PACs in this raw-SVD iteration.

2023-03-22 00:41 UTC, adamgreig requested changes
Thanks for putting this together and updating the README too!

Just a few minor nits here. I also wondered if it would make sense to combine the 562/563/573 but it seems the 573 adds the entire security manager so probably not.

2023-03-22 00:41 UTC, adamgreig commented on README.md
> +### If adding a new STM32 family (not just a new device to an existing family), complete
```suggestion
If adding a new STM32 family (not just a new device to an existing family), complete
```

2023-03-22 00:41 UTC, adamgreig commented on README.md
> +  and `svdtools` dependencies. Example command: `python .\scripts\matchperipherals.py peripherals/rcc devices/stm32h562.yaml`
```suggestion
  and `svdtools` dependencies.
  Example command: `python scripts/matchperipherals.py peripherals/rcc devices/stm32h562.yaml`
```

2023-03-22 00:41 UTC, adamgreig commented on stm32_part_table.yaml
> +    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h5-series.html
```suggestion
    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h563-573.html
```

2023-03-22 00:41 UTC, adamgreig commented on stm32_part_table.yaml
> +    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h5-series.html
```suggestion
    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h562.html
```

2023-03-22 00:41 UTC, adamgreig commented on stm32_part_table.yaml
> +    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h5-series.html
```suggestion
    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h503.html
```

2023-03-22 00:41 UTC, adamgreig commented on stm32_part_table.yaml
> +    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h5-series.html
```suggestion
    url: https://www.st.com/en/microcontrollers-microprocessors/stm32h563-573.html
```

2023-03-22 00:57 UTC, David-OConnor commented
Good stuff; I appreciate it!

2023-03-22 01:01 UTC, adamgreig approved these changes
thanks!

bors r+

2023-03-22 01:11 UTC, merged

2023-03-22 15:01 UTC, hydra commented
Just trying this out and it seems that most of the registers and register blocks that I've looked have have the peripheral name prefixed to them.

e.g.

H5:
https://github.com/stm32-rs/stm32-rs-nightlies/tree/master/stm32h5/src/stm32h563/dbgmcu

vs. H7:
https://github.com/stm32-rs/stm32-rs-nightlies/tree/master/stm32h7/src/stm32h743/dbgmcu

H5 screenshot:

2023-04-24 20:26 UTC, joaomorenorf commented
Hello,
I wasn't able to compile. Do you have a example project?
Best regards,
João

2023-04-24 21:48 UTC, David-OConnor commented
Hi. The issue is most likely that there is no published H5 PAC. I may publish an interim one, then do a new release of this HAL to make it work.